
spring:
  application:
    name: PlistBackend
  profiles:
    include: secret

  datasource:
    driver-class-name: ${db_class_name}
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}

  jpa:
    hibernate:
      ddl-auto: ${ddl_auto}
    open-in-view: true
    show-sql: true
    database: ${database}
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ${client_id}
            client-secret: ${client_secret}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile, email
  jwt:
    secret: ${jwt_secret}

youtube-api:
  url: "https://www.googleapis.com/youtube/v3/search?key=%s&q=%s&type=%s&part=%s&order=%s&relevanceLanguage=%s&videoEmbeddable=%s&maxResults=%d&topicId=%s"
  type: "video" # 검색할 타입
  part: "snippet" # 응답에 포함될 내용
  maxResults: 50 # 페이지 당 보여주는 응답 갯수 범위 0~50
  order: "viewCount" # 조회수가 많은 순서대로 정렬
  relevanceLanguage: "ko" # 가장 관련있는 언어로 검색
  videoEmbeddable: "true" # 웹 페이지에서 재생가능한 동영상만 검색
  topicId: "/m/04rlf" # 검색 결과를 음악으로 제한함
  apiKey: ${youtube_api_key} # 자신의 API 키

