spring:
  application:
    name: PlistBackend
  profiles:
    include: secret

  datasource:
    driver-class-name: ${db_class_name}
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}

  jpa:
    hibernate:
      ddl-auto: ${ddl_auto}
    open-in-view: true
    show-sql: true
    database: ${database}
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ${client_id}
            client-secret: ${client_secret}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile, email
  jwt:
    secret: ${jwt_secret}
youtube_data_api_key: ${youtube_data_api_key}
